[package]
name = "platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
specs = "0.20.0"
specs-derive = "0.4.1"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["image"]

